services:
  frontend:
    build:
      context: ~/layerrs/web #Path to frontend dockerfile
      dockerfile: Dockerfile
    env_file:
      - ~/.env
    image: layerrs-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
       - app-network
    restart: always

  backend:
    build:
      context: ~/layerrs #Path to backend dockerfile
      dockerfile: Dockerfile
    env_file:
      - ~/.env.backend.prod
    image: layerrs-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge