CREATE TABLE artist (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    bio TEXT,
    r2_image_key VARCHAR(64),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- CREATE
INSERT INTO artist (name, username, email) VALUES ('trent', 'trent101', 'trentjkelly1@gmail.com');

--READ
SELECT * FROM artist WHERE id=2;