name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Go + SvelteKit app
        uses: shimataro/ssh-key-action@v2
        with:
          host: ${{ secrets.SSH_HOST }} 
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd ~/layerrs
            docker-compose down
            git pull origin main
            docker-compose up --build
            echo "Successful deployment"
          docker-compose down
          git pull origin main
          docker-compose up --build
          echo "Successful deployment"
